### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by mahmooddagga** [ZieIony/NaturalDateFormat#11]
i will provide you Arabic translation string.xml file soon

**Comment by ZieIony** [comment]
Cool, thanks!

**Comment by mahmooddagga** [comment]
@ZieIony  

Url for xml  -ar
[http://txt.do/5eags](http://txt.do/5eags)

**Comment by mahmooddagga** [comment]
`<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingQuantity">
`
