### ISSUE TITLE
Question - Difference below 24 hrs, returns today in DAYS format

### ISSUE THREAD

**Issue by IRMobydick** [ZieIony/NaturalDateFormat#13]
Hi there, I have a problem
I've start an event in `1477831898000` that ends in `1480078298000`
Today time stamp is `1477901605205`

I'm using `RelativeDateFormat` like this below:

    RelativeDateFormat relativeDateFormat = new RelativeDateFormat(mContext, NaturalDateFormat.DAYS);
   
    if (StartDate < 1000000000000L)  StartDate *= 1000;
    if (EndDate < 1000000000000L) EndDate *= 1000;

    eventStartDate.setText(relativeDateFormat.format(StartDate));
    eventEndDate.setText(relativeDateFormat.format(EndDate));

In fact, event start day was yesterday! but library show this as Today!
You know what time difference between today and start time is under 24 hours but it started in yesterday!

Am I wrong?

**Comment by ZieIony** [comment]
fixed
