### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by andkulikov** [ZieIony/NaturalDateFormat#5]
Hello! I will be happy to add russian translation, but russian have some peculiarity (and probably some of other languages too). 

We have different form of noun for numerals depends of number itself. For example:
1 hour ago - 1 час назад 
2 hours ago - 2 часа назад
5 hours ago - 5 часов назад

in 1 minute - через 1 минуту
in 2 minutes - через 2 минуты
in 5 minutes - через 5 минут

so there should be array of strings

``` java
hours = {"час", "часа", "часов"}
minutes = {"минуту", "минуты", "минут"}
```

and real function for Russian will looks like:

``` java
int getIndexOfString(int number) {
  if (number % 10 == 1 && number % 100 != 11) {
    return 0;
  } else if (number % 10 >= 2 && number % 10 <= 4 && 
               (number % 100 < 10 || number % 100 >= 20)) {
    return 1;
  } else {
    return 2;
  }
}
```

looks quite strange, yep?) but its rules of language

for example for English we have the same logic but not so complex

``` java
hours = {"hour", "hours"}
minutes = {"minute", "minutes"}
```

``` java
int getIndexOfString(int number) {
  if (number == 1) {
    return 0;
  } else {
    return 1;
  }
}
```

Some kind of refactoring is required to implement it.

**Comment by ZieIony** [comment]
It's not strange, Polish has more forms as well. Check out the Polish translation. For example:

```
<plurals name="carbon_hoursAgo">
    <item quantity="one">godzinę temu</item>
    <item quantity="few">%d godziny temu</item>
    <item quantity="many">%d godzin temu</item>
    <item quantity="other">%d godziny temu</item>
</plurals>
```

So it has cases for 1, then for 2, 3, 4, 22, 23, 24, etc, then many is for other integral numbers and other is for real numbers.

In Russian it would be:

```
<plurals name="carbon_hoursAgo">
    <item quantity="one">час назад</item>
    <item quantity="few">%d часа назад</item>    <!-- 3 часа назад -->
    <item quantity="many">%d часов назад</item>    <!-- 7 часов назад -->
    <item quantity="other">%d часа назад</item>    <!-- 0.5 часа назад -->
</plurals>
```

As far as I know Russian forms for small integers and reals are identical.

**Comment by ZieIony** [comment]
Russian translation is now available and as far as I know - it's correct
